Fix language standard used for the clang_generator tool
Use -std=gnu++17 instead of -std=c++17 when possible.
See the added comment for details.

Without the fix the build fails with:
replacement_library.sapi.guest.h:21:67: error: unknown type name '_Bool'
   21 |                                              int64_t a3, char a4, _Bool a5,
      |                                                                   ^

I did not find any other test that does not use C and uses
a header file for the sandboxed library. So used the replacement_library test.

PiperOrigin-RevId: 792096242
Change-Id: I0c34dbfc0207deba405e01928da8c45f858f0f8b